version: '3.8'

services:
  ml-pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: retail_24-ml-pipeline-1
    volumes:
      - ./data:/app/data
      - models:/app/models
    environment:
      - DOCKER_CONTAINER=true
      - MODEL_DIR=/app/models
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_CLUSTER=${MONGODB_CLUSTER}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - mongodb
    restart: unless-stopped

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: retail_24-streamlit-app-1
    ports:
      - "8501"
    volumes:
      - models:/app/models
    environment:
      - DOCKER_CONTAINER=true
      - MODEL_DIR=/app/models
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_CLUSTER=${MONGODB_CLUSTER}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - mongodb
    restart: "no"  # ✅ Changed from "unless-stopped" to prevent restart after successful exit

  mongodb:
    image: mongo:latest
    container_name: retail_24-mongodb-1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    restart: unless-stopped

volumes:
  models:
    driver: local
  mongodb_data:
    driver: local
